import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:encrypt/encrypt.dart' as encrypt;
import 'dart:convert'; // Untuk Base64 encoding/decoding
import 'dart:math'; // Untuk Random (saat ini tidak digunakan langsung untuk secure random, tapi untuk generateKeyAndIV yang menggunakannya)

// ===========================
// 🔹 AES CIPHER PAGE
// ===========================
class AesPage extends StatefulWidget {
  const AesPage({super.key});

  @override
  State<AesPage> createState() => _AesPageState();
}

enum CipherMode { encrypt, decrypt }

class _AesPageState extends State<AesPage> {
  // Controllers untuk input kunci, IV, teks input, dan output
  final TextEditingController _keyController = TextEditingController();
  final TextEditingController _ivController = TextEditingController();
  final TextEditingController _messageController = TextEditingController();
  final TextEditingController _cipherInputController = TextEditingController();

  String _result = ''; // Hasil akhir enkripsi/dekripsi

  CipherMode _currentMode = CipherMode.encrypt; // Mode default
  String _errorMessage = ''; // Untuk menampilkan pesan error
  bool _isAutoGenerated = false; // Menandakan apakah kunci/IV dibuat otomatis

  // Keys for SharedPreferences
  static const String _aesKey = 'aesKey';
  static const String _aesIv = 'aesIv';
  static const String _aesMessage = 'aesMessage';
  static const String _aesCipherInput = 'aesCipherInput';
  static const String _aesCurrentMode = 'aesCurrentMode';
  static const String _aesIsAutoGenerated = 'aesIsAutoGenerated';

  @override
  void initState() {
    super.initState();
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.dark.copyWith(
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light,
        statusBarColor: Colors.white,
      ),
    );
    _loadData();

    _keyController.addListener(_saveData);
    _ivController.addListener(_saveData);
    _messageController.addListener(_saveData);
    _cipherInputController.addListener(_saveData);
  }

  @override
  void dispose() {
    _keyController.removeListener(_saveData);
    _ivController.removeListener(_saveData);
    _messageController.removeListener(_saveData);
    _cipherInputController.removeListener(_saveData);

    _keyController.dispose();
    _ivController.dispose();
    _messageController.dispose();
    _cipherInputController.dispose();
    super.dispose();
  }

  // ============================
  // 💾 Fungsi untuk menyimpan data ke SharedPreferences
  // ============================
  Future<void> _saveData() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_aesKey, _keyController.text);
    await prefs.setString(_aesIv, _ivController.text);
    await prefs.setString(_aesMessage, _messageController.text);
    await prefs.setString(_aesCipherInput, _cipherInputController.text);
    await prefs.setInt(_aesCurrentMode, _currentMode.index);
    await prefs.setBool(_aesIsAutoGenerated, _isAutoGenerated);
  }

  // ============================
  // 📥 Fungsi untuk memuat data dari SharedPreferences
  // ============================
  Future<void> _loadData() async {
    final prefs = await SharedPreferences.getInstance();
    setState(() {
      _keyController.text = prefs.getString(_aesKey) ?? '';
      _ivController.text = prefs.getString(_aesIv) ?? '';
      _messageController.text = prefs.getString(_aesMessage) ?? '';
      _cipherInputController.text = prefs.getString(_aesCipherInput) ?? '';
      _currentMode = CipherMode.values[prefs.getInt(_aesCurrentMode) ?? 0];
      _isAutoGenerated = prefs.getBool(_aesIsAutoGenerated) ?? false;

      // Re-calculate result if keys/IV and messages are present
      // Only process silently if there's actual data to process
      if (_keyController.text.isNotEmpty && _ivController.text.isNotEmpty) {
        if (_currentMode == CipherMode.encrypt &&
            _messageController.text.isNotEmpty) {
          _processCipher(silent: true);
        } else if (_currentMode == CipherMode.decrypt &&
            _cipherInputController.text.isNotEmpty) {
          _processCipher(silent: true);
        }
      }
    });
  }

  // ============================
  // 🔄 Fungsi untuk mengosongkan semua input dan hasil
  // ============================
  void _clearAll() {
    setState(() {
      _keyController.clear();
      _ivController.clear();
      _messageController.clear();
      _cipherInputController.clear();
      _result = '';
      _currentMode = CipherMode.encrypt;
      _errorMessage = '';
      _isAutoGenerated = false;
    });
    _saveData();
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Semua input dan hasil telah dikosongkan!'),
        ),
      );
    }
  }

  // ========================================
  // 🔑 Key and IV Generation
  // ========================================
  void _generateKeyAndIV({bool silent = false}) {
    setState(() {
      _errorMessage = '';
      _isAutoGenerated = true; // Set to true when auto-generating
    });

    try {
      // Generate a random 256-bit (32-byte) key
      final keyBytes = encrypt.Key.fromSecureRandom(32);
      _keyController.text = base64.encode(keyBytes.bytes);

      // Generate a random 128-bit (16-byte) IV
      final ivBytes = encrypt.IV.fromSecureRandom(16);
      _ivController.text = base64.encode(ivBytes.bytes);

      _saveData();
      if (!silent && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Kunci dan IV AES otomatis berhasil dibuat!'),
          ),
        );
      }
    } catch (e) {
      if (!silent) {
        setState(() {
          _errorMessage = 'Gagal membuat kunci/IV otomatis: $e';
        });
      }
    }
  }

  // ========================================
  // 🔒 Enkripsi AES
  // ========================================
  String _encryptMessage(String plaintext) {
    if (_keyController.text.isEmpty || _ivController.text.isEmpty) {
      setState(() {
        _errorMessage = 'Kunci dan IV harus diisi.';
      });
      return '';
    }

    try {
      final keyBytes = base64.decode(_keyController.text);
      final ivBytes = base64.decode(_ivController.text);

      if (keyBytes.length != 32) {
        // AES-256 requires 32 bytes (256 bits)
        setState(() {
          _errorMessage = 'Panjang kunci harus 32 byte (256 bit) Base64.';
        });
        return '';
      }
      if (ivBytes.length != 16) {
        // AES block size is 16 bytes (128 bits)
        setState(() {
          _errorMessage = 'Panjang IV harus 16 byte (128 bit) Base64.';
        });
        return '';
      }

      final key = encrypt.Key(keyBytes);
      final iv = encrypt.IV(ivBytes);

      final encrypter = encrypt.Encrypter(
        encrypt.AES(key, mode: encrypt.AESMode.cbc, padding: 'PKCS7'),
      );

      final encrypted = encrypter.encrypt(plaintext, iv: iv);
      return encrypted.base64;
    } catch (e) {
      setState(() {
        _errorMessage =
            'Gagal enkripsi: Pastikan kunci dan IV valid Base64. $e';
      });
      return '';
    }
  }

  // ========================================
  // 🔓 Dekripsi AES
  // ========================================
  String _decryptMessage(String ciphertext) {
    if (_keyController.text.isEmpty || _ivController.text.isEmpty) {
      setState(() {
        _errorMessage = 'Kunci dan IV harus diisi.';
      });
      return '';
    }

    try {
      final keyBytes = base64.decode(_keyController.text);
      final ivBytes = base64.decode(_ivController.text);

      if (keyBytes.length != 32) {
        setState(() {
          _errorMessage = 'Panjang kunci harus 32 byte (256 bit) Base64.';
        });
        return '';
      }
      if (ivBytes.length != 16) {
        setState(() {
          _errorMessage = 'Panjang IV harus 16 byte (128 bit) Base64.';
        });
        return '';
      }

      final key = encrypt.Key(keyBytes);
      final iv = encrypt.IV(ivBytes);

      final encrypter = encrypt.Encrypter(
        encrypt.AES(key, mode: encrypt.AESMode.cbc, padding: 'PKCS7'),
      );

      final decrypted = encrypter.decrypt64(ciphertext, iv: iv);
      return decrypted;
    } catch (e) {
      setState(() {
        _errorMessage =
            'Gagal dekripsi: Pastikan kunci, IV, dan ciphertext valid Base64. $e';
      });
      return '';
    }
  }

  // ========================================
  // ⚙️ Proses Enkripsi/Dekripsi Utama
  // ========================================
  void _processCipher({bool silent = false}) {
    setState(() {
      _errorMessage = '';
    });

    if (_keyController.text.isEmpty || _ivController.text.isEmpty) {
      if (!silent) {
        setState(() {
          _errorMessage =
              'Harap masukkan atau buat kunci dan IV AES terlebih dahulu.';
        });
      }
      return;
    }

    if (_currentMode == CipherMode.encrypt) {
      final message = _messageController.text.trim();
      if (message.isEmpty) {
        if (!silent) {
          setState(() {
            _errorMessage = 'Masukkan teks untuk dienkripsi!';
          });
        }
        return;
      }
      final encrypted = _encryptMessage(message);
      if (encrypted.isNotEmpty) {
        setState(() {
          _result = encrypted;
          _cipherInputController.text = encrypted;
        });
      }
    } else {
      // CipherMode.decrypt
      final cipherInput = _cipherInputController.text.trim();
      if (cipherInput.isEmpty) {
        if (!silent) {
          setState(() {
            _errorMessage = 'Masukkan teks terenkripsi untuk didekripsi!';
          });
        }
        return;
      }
      final decrypted = _decryptMessage(cipherInput);
      if (decrypted.isNotEmpty) {
        setState(() {
          _result = decrypted;
          _messageController.text = decrypted;
        });
      }
    }
    _saveData();
    if (!silent && _errorMessage.isEmpty && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            _currentMode == CipherMode.encrypt
                ? 'Pesan berhasil dienkripsi!'
                : 'Pesan berhasil didekripsi!',
          ),
        ),
      );
    }
  }

  // ============================
  // 📝 Fungsi untuk membuat pesan yang akan dibagikan
  // ============================
  String _buildMessageForSharing() {
    String keyInfo = '';
    if (_keyController.text.isNotEmpty && _ivController.text.isNotEmpty) {
      keyInfo = '''
*Kunci (Base64):* ```${_keyController.text}```
*IV (Base64):* ```${_ivController.text}```
''';
    }

    if (_currentMode == CipherMode.encrypt) {
      return '''
🔐 *Pesan Terenkripsi (AES-256 CBC)*

━━━━━━━━━━━━━━━
$keyInfo
*Hasil Enkripsi (Base64):*
```$_result```

📜 *Petunjuk Dekripsi:*
Gunakan kunci dan IV yang sama untuk mendekripsi pesan ini.
━━━━━━━━━━━━━━━

📘 _Pesan ini dibuat otomatis dari aplikasi Enkripsi by Defri_
''';
    } else {
      return '''
🔓 *Pesan Terdekripsi (AES-256 CBC)*

━━━━━━━━━━━━━━━
$keyInfo
*Hasil Dekripsi:*
```$_result```

🔑 *Petunjuk:*
Ini adalah pesan asli setelah dekripsi menggunakan kunci dan IV yang benar.
━━━━━━━━━━━━━━━

📘 _Pesan ini dibuat otomatis dari aplikasi Enkripsi by Defri_
''';
    }
  }

  // ========================================
  // 💬 Kirim ke WhatsApp
  // ========================================
  Future<void> _sendToWhatsApp() async {
    if (_result.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Belum ada hasil yang bisa dikirim.')),
        );
      }
      return;
    }

    final message = _buildMessageForSharing();
    // WhatsApp doesn't render ``` as code blocks, remove them
    final String whatsappMessage = message.replaceAll('```', '');

    await Clipboard.setData(ClipboardData(text: whatsappMessage));
    final encodedMessage = Uri.encodeComponent(whatsappMessage);
    final whatsappUri = Uri.parse("whatsapp://send?text=$encodedMessage");

    try {
      if (await canLaunchUrl(whatsappUri)) {
        await launchUrl(whatsappUri, mode: LaunchMode.externalApplication);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Pesan disalin dan WhatsApp dibuka!')),
          );
        }
      } else {
        final fallbackUrl = Uri.parse("https://wa.me/?text=$encodedMessage");
        await launchUrl(fallbackUrl, mode: LaunchMode.externalApplication);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Gagal membuka WhatsApp: $e')));
      }
    }
  }

  // ========================================
  // 📧 Kirim ke Gmail
  // ========================================
  Future<void> _sendToGmail() async {
    if (_result.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Belum ada hasil yang bisa dikirim.')),
        );
      }
      return;
    }

    final String message = _buildMessageForSharing();
    final String subject =
        _currentMode == CipherMode.encrypt
            ? '🔐 Encrypted Message (AES)'
            : '🔓 Decrypted Message (AES)';
    final String encodedSubject = Uri.encodeComponent(subject);
    final String encodedBody = Uri.encodeComponent(message);

    final Uri mailtoUri = Uri.parse(
      'mailto:?subject=$encodedSubject&body=$encodedBody',
    );

    try {
      await launchUrl(mailtoUri, mode: LaunchMode.externalApplication);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Membuka aplikasi email...')),
        );
      }
    } catch (e) {
      final webGmailUrl = Uri.parse(
        'https://mail.google.com/mail/?view=cm&fs=1&su=$encodedSubject&body=$encodedBody',
      );
      try {
        await launchUrl(webGmailUrl, mode: LaunchMode.platformDefault);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Membuka Gmail versi web...')),
          );
        }
      } catch (e2) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Gagal membuka Gmail: $e2')));
        }
      }
    }
  }

  // ========================================
  // 🧱 UI Helper Widgets (Konsisten dengan halaman cipher lainnya)
  // ========================================

  Widget _buildTextField(
    TextEditingController controller,
    String hintText,
    TextInputType keyboardType, {
    int? maxLines,
    bool readOnly = false,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha((255 * 0.08).round()),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: TextField(
        controller: controller,
        keyboardType: keyboardType,
        textInputAction: TextInputAction.done,
        style: const TextStyle(color: Colors.black87),
        maxLines: maxLines,
        readOnly: readOnly,
        decoration: InputDecoration(
          hintText: hintText,
          hintStyle: TextStyle(color: Colors.grey[500]),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 16,
            vertical: 14,
          ),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFF041413), width: 2),
          ),
          filled: true,
          fillColor: Colors.white,
        ),
      ),
    );
  }

  Widget _buildActionButton(String text, VoidCallback onPressed, Color color) {
    return ElevatedButton(
      onPressed: onPressed,
      style: ElevatedButton.styleFrom(
        backgroundColor: color,
        padding: const EdgeInsets.symmetric(horizontal: 25, vertical: 10),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        shadowColor: Colors.black.withAlpha((255 * 0.3).round()),
        elevation: 8,
      ),
      child: Text(
        text,
        textAlign: TextAlign.center,
        style: const TextStyle(
          fontSize: 15,
          color: Colors.white,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildResultContainer(String text) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha((255 * 0.1).round()),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: SelectableText(
        text,
        style: const TextStyle(color: Colors.black87, fontSize: 16),
      ),
    );
  }

  Widget _buildCopyButtons() {
    return Row(
      children: [
        Expanded(
          child: ElevatedButton.icon(
            onPressed: () {
              Clipboard.setData(ClipboardData(text: _result));
              if (mounted) {
                ScaffoldMessenger.of(
                  context,
                ).showSnackBar(const SnackBar(content: Text('Hasil disalin!')));
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF041413),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              shadowColor: Colors.black.withAlpha((255 * 0.2).round()),
              elevation: 4,
            ),
            icon: const Icon(Icons.copy, size: 18),
            label: const Text(
              'Salin Hasil',
              style: TextStyle(fontWeight: FontWeight.w500),
            ),
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: ElevatedButton.icon(
            onPressed: () {
              final info =
                  _currentMode == CipherMode.encrypt
                      ? 'Gunakan kunci dan IV yang sama untuk mendekripsi pesan ini.'
                      : 'Ini adalah pesan asli setelah dekripsi menggunakan kunci dan IV yang benar.';
              Clipboard.setData(ClipboardData(text: info));
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Petunjuk disalin!')),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF041413),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              shadowColor: Colors.black.withAlpha((255 * 0.2).round()),
              elevation: 4,
            ),
            icon: const Icon(Icons.info_outline, size: 18),
            label: const Text(
              'Salin Petunjuk',
              style: TextStyle(fontWeight: FontWeight.w500),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSocialButton(String assetPath, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: 65,
        height: 65,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withAlpha((255 * 0.15).round()),
              blurRadius: 8,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Center(
          child: SvgPicture.asset(assetPath, width: 32, height: 32),
        ),
      ),
    );
  }

  // ========================================
  // 🧱 UI Utama
  // ========================================
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      backgroundColor: const Color(0xFFE6E6E6),
      body: SafeArea(
        child: Column(
          children: [
            // HEADER
            Container(
              height: 70,
              width: double.infinity,
              color: const Color(0xFF041413),
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Positioned(
                    left: 12,
                    child: IconButton(
                      icon: const Icon(
                        Icons.arrow_back_ios_new_rounded,
                        color: Colors.white,
                      ),
                      iconSize: 24,
                      onPressed: () => Navigator.pop(context),
                    ),
                  ),
                  SvgPicture.asset(
                    'assets/images/logoenkripsiapps.svg',
                    width: 50,
                    height: 50,
                  ),
                  Positioned(
                    right: 12,
                    child: IconButton(
                      icon: const Icon(Icons.refresh, color: Colors.white),
                      iconSize: 24,
                      onPressed: _clearAll,
                    ),
                  ),
                ],
              ),
            ),

            // Mode Toggle
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 20.0,
                vertical: 15.0,
              ),
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.all(4),
                decoration: BoxDecoration(
                  color: Colors.grey[200],
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withAlpha((255 * 0.08).round()),
                      blurRadius: 6,
                      offset: const Offset(0, 3),
                    ),
                  ],
                ),
                child: LayoutBuilder(
                  builder: (context, constraints) {
                    final buttonWidth = (constraints.maxWidth - 8) / 2;

                    return ToggleButtons(
                      isSelected: [
                        _currentMode == CipherMode.encrypt,
                        _currentMode == CipherMode.decrypt,
                      ],
                      onPressed: (index) {
                        setState(() {
                          _currentMode =
                              index == 0
                                  ? CipherMode.encrypt
                                  : CipherMode.decrypt;
                          _errorMessage = '';
                          // Clear result when switching mode to avoid confusion
                          _result = '';
                          // If switching to decrypt, ensure message controller is cleared
                          if (_currentMode == CipherMode.decrypt) {
                            _messageController.clear();
                          } else {
                            // If switching to encrypt, ensure cipher input controller is cleared
                            _cipherInputController.clear();
                          }
                        });
                        _saveData();
                      },
                      borderRadius: BorderRadius.circular(10),
                      selectedColor: Colors.white,
                      color: Colors.black87,
                      fillColor: const Color(0xFF041413),
                      borderColor: Colors.transparent,
                      selectedBorderColor: Colors.transparent,
                      splashColor: const Color(
                        0xFF041413,
                      ).withAlpha((255 * 0.2).round()),
                      highlightColor: const Color(
                        0xFF041413,
                      ).withAlpha((255 * 0.1).round()),
                      children: [
                        SizedBox(
                          width: buttonWidth,
                          child: const Center(
                            child: Padding(
                              padding: EdgeInsets.symmetric(
                                horizontal: 10,
                                vertical: 10,
                              ),
                              child: Text(
                                'Enkripsi',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: buttonWidth,
                          child: const Center(
                            child: Padding(
                              padding: EdgeInsets.symmetric(
                                horizontal: 10,
                                vertical: 10,
                              ),
                              child: Text(
                                'Dekripsi',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
            ),

            // BODY
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (_errorMessage.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 15.0),
                        child: Text(
                          _errorMessage,
                          style: const TextStyle(
                            color: Colors.red,
                            fontSize: 14,
                          ),
                        ),
                      ),
                    const Text(
                      'Input Kunci AES (Base64):',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: Colors.black87,
                      ),
                    ),
                    const SizedBox(height: 10),
                    _buildTextField(
                      _keyController,
                      'Kunci AES (256-bit / 32 byte Base64)',
                      TextInputType.text,
                      // Read-only jika otomatis DAN sedang dalam mode enkripsi
                      readOnly:
                          _isAutoGenerated &&
                          _currentMode == CipherMode.encrypt,
                    ),
                    const SizedBox(height: 10),
                    const Text(
                      'Input IV (Initialization Vector, Base64):',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: Colors.black87,
                      ),
                    ),
                    const SizedBox(height: 10),
                    _buildTextField(
                      _ivController,
                      'IV (128-bit / 16 byte Base64)',
                      TextInputType.text,
                      // Read-only jika otomatis DAN sedang dalam mode enkripsi
                      readOnly:
                          _isAutoGenerated &&
                          _currentMode == CipherMode.encrypt,
                    ),
                    const SizedBox(height: 20),

                    // Tombol Buat Kunci hanya muncul di mode Enkripsi
                    if (_currentMode == CipherMode.encrypt)
                      Row(
                        children: [
                          Expanded(
                            child: _buildActionButton(
                              'Buat Kunci & IV Otomatis',
                              () => _generateKeyAndIV(silent: false),
                              const Color(0xFF455A64), // Warna biru-abu gelap
                            ),
                          ),
                        ],
                      ),
                    const SizedBox(height: 24),

                    if (_currentMode == CipherMode.encrypt) ...[
                      const Text(
                        'Masukkan teks untuk dienkripsi:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildTextField(
                        _messageController,
                        'Tulis teks...',
                        TextInputType.text,
                        maxLines: 3,
                      ),
                      const SizedBox(height: 20),
                      Center(
                        // Menengahkan tombol
                        child: _buildActionButton(
                          'Enkripsi Sekarang',
                          _processCipher,
                          const Color(0xFF041413),
                        ),
                      ),
                      const SizedBox(height: 24),
                      const Text(
                        'Hasil Enkripsi (Base64):',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildResultContainer(
                        _result.isEmpty
                            ? 'Hasil akan muncul di sini...'
                            : _result,
                      ),
                    ] else ...[
                      // UI untuk Dekripsi
                      const Text(
                        'Masukkan teks terenkripsi (Base64):',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildTextField(
                        _cipherInputController,
                        'Tulis teks terenkripsi (Base64)',
                        TextInputType.text,
                        maxLines: 3,
                      ),
                      const SizedBox(height: 20),
                      Center(
                        // Menengahkan tombol
                        child: _buildActionButton(
                          'Dekripsi Sekarang',
                          _processCipher,
                          const Color(0xFF041413),
                        ),
                      ),
                      const SizedBox(height: 24),
                      const Text(
                        'Hasil Dekripsi:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildResultContainer(
                        _result.isEmpty
                            ? 'Hasil akan muncul di sini...'
                            : _result,
                      ),
                    ],
                    const SizedBox(height: 10),
                    if (_result.isNotEmpty) _buildCopyButtons(),

                    const SizedBox(height: 30),
                    const Divider(color: Colors.black12, thickness: 1.5),
                    const SizedBox(height: 8),
                    const Text(
                      '📘 Penjelasan Kriptografi:',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: Colors.black87,
                      ),
                    ),
                    const SizedBox(height: 6),
                    const SelectableText(
                      'AES (Advanced Encryption Standard) adalah algoritma enkripsi simetris. '
                      'Ini berarti kunci yang sama digunakan untuk enkripsi dan dekripsi. '
                      'Kami menggunakan AES-256 (kunci 256-bit), mode CBC (Cipher Block Chaining), '
                      'dan padding PKCS7. IV (Initialization Vector) adalah nilai acak yang '
                      'harus unik untuk setiap operasi enkripsi, tetapi tidak perlu dirahasiakan. '
                      'IV mencegah pola yang sama menghasilkan ciphertext yang sama untuk plaintext yang sama. '
                      'Semua kunci, IV, dan ciphertext disajikan dalam format Base64.',
                      style: TextStyle(color: Colors.black87, height: 1.4),
                    ),
                    const SizedBox(height: 32),
                    Center(
                      child: Column(
                        children: [
                          const Text(
                            'Kirim hasil ke',
                            style: TextStyle(
                              fontSize: 17,
                              fontWeight: FontWeight.w700,
                              color: Colors.black87,
                            ),
                          ),
                          const SizedBox(height: 10),
                          Container(
                            width: 180,
                            height: 1.5,
                            color: Colors.black26,
                          ),
                          const SizedBox(height: 20),
                          // 🔗 Sosial
                          Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              _buildSocialButton(
                                'assets/images/wa.svg',
                                _sendToWhatsApp,
                              ),
                              const SizedBox(width: 40),
                              _buildSocialButton(
                                'assets/images/gmail.svg',
                                _sendToGmail,
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
