// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIzwKKOVkoWynV3SkJfrLRBWFaQmlLOw',
    appId: '1:556913456151:web:821614d1cb8974349c1852',
    messagingSenderId: '556913456151',
    projectId: 'encryptionapps',
    authDomain: 'encryptionapps.firebaseapp.com',
    storageBucket: 'encryptionapps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_x68Cqbn-6nwATez-IicTg-TY1ocFMw',
    appId: '1:556913456151:android:75260315d9cdc3db9c1852',
    messagingSenderId: '556913456151',
    projectId: 'encryptionapps',
    storageBucket: 'encryptionapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeQ_BUNZgUtK0YrzqEQghrcXiBrFAU0o',
    appId: '1:556913456151:ios:88adc80be291ad8d9c1852',
    messagingSenderId: '556913456151',
    projectId: 'encryptionapps',
    storageBucket: 'encryptionapps.firebasestorage.app',
    iosBundleId: 'com.example.encryptionapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAeQ_BUNZgUtK0YrzqEQghrcXiBrFAU0o',
    appId: '1:556913456151:ios:88adc80be291ad8d9c1852',
    messagingSenderId: '556913456151',
    projectId: 'encryptionapps',
    storageBucket: 'encryptionapps.firebasestorage.app',
    iosBundleId: 'com.example.encryptionapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFIzwKKOVkoWynV3SkJfrLRBWFaQmlLOw',
    appId: '1:556913456151:web:569e370a95e14f829c1852',
    messagingSenderId: '556913456151',
    projectId: 'encryptionapps',
    authDomain: 'encryptionapps.firebaseapp.com',
    storageBucket: 'encryptionapps.firebasestorage.app',
  );
}
