import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:math'; // Untuk Random

// ===========================
// 🔹 RSA CIPHER PAGE
// ===========================
class RsaPage extends StatefulWidget {
  const RsaPage({super.key});

  @override
  State<RsaPage> createState() => _RsaPageState();
}

enum CipherMode { encrypt, decrypt }

class _RsaPageState extends State<RsaPage> {
  // Controllers untuk input kunci
  final TextEditingController _pController = TextEditingController();
  final TextEditingController _qController = TextEditingController();
  final TextEditingController _eInputController =
      TextEditingController(); // Diganti nama untuk kejelasan

  // Controllers untuk teks input dan output
  final TextEditingController _messageController = TextEditingController();
  final TextEditingController _cipherInputController = TextEditingController();

  String _result = ''; // Hasil akhir enkripsi/dekripsi

  // Nilai kunci yang dihitung (BigInt)
  BigInt? _n;
  BigInt? _phi;
  BigInt? _eValue; // Variabel baru untuk menyimpan nilai BigInt dari 'e'
  BigInt? _d;

  CipherMode _currentMode = CipherMode.encrypt; // Mode default
  bool _generatedKeysVisible =
      false; // Untuk menampilkan/menyembunyikan kunci yang dihasilkan
  String _errorMessage = ''; // Untuk menampilkan pesan error
  bool _isAutoGenerated = false; // Menandakan apakah kunci dibuat otomatis

  // Keys for SharedPreferences
  static const String _pKey = 'rsaP';
  static const String _qKey = 'rsaQ';
  static const String _eInputKey = 'rsaEInput'; // Key untuk teks input 'e'
  static const String _eValueKey = 'rsaEValue'; // Key untuk nilai BigInt 'e'
  static const String _messageKey = 'rsaMessage';
  static const String _cipherInputKey = 'rsaCipherInput';
  static const String _currentModeKey = 'rsaCipherMode';
  static const String _nKey = 'rsaN';
  static const String _phiKey = 'rsaPhi';
  static const String _dKey = 'rsaD';
  static const String _generatedKeysVisibleKey = 'rsaGeneratedKeysVisible';
  static const String _isAutoGeneratedKey = 'rsaIsAutoGenerated';

  @override
  void initState() {
    super.initState();
    // Atur status bar untuk halaman ini
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.dark.copyWith(
        statusBarIconBrightness: Brightness.dark, // Untuk Android (ikon gelap)
        statusBarBrightness: Brightness.light, // Untuk iOS (ikon gelap)
        statusBarColor: Colors.white, // Status bar wajib putih
      ),
    );

    _loadData(); // Muat data tersimpan

    // Tambahkan listener untuk auto-save
    _pController.addListener(_saveData);
    _qController.addListener(_saveData);
    _eInputController.addListener(_saveData); // Diperbarui
    _messageController.addListener(_saveData);
    _cipherInputController.addListener(_saveData);
  }

  @override
  void dispose() {
    // Hapus listener untuk mencegah memory leak
    _pController.removeListener(_saveData);
    _qController.removeListener(_saveData);
    _eInputController.removeListener(_saveData); // Diperbarui
    _messageController.removeListener(_saveData);
    _cipherInputController.removeListener(_saveData);

    _pController.dispose();
    _qController.dispose();
    _eInputController.dispose(); // Diperbarui
    _messageController.dispose();
    _cipherInputController.dispose();
    super.dispose();
  }

  // ============================
  // 💾 Fungsi untuk menyimpan data ke SharedPreferences
  // ============================
  Future<void> _saveData() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_pKey, _pController.text);
    await prefs.setString(_qKey, _qController.text);
    await prefs.setString(
      _eInputKey,
      _eInputController.text,
    ); // Simpan teks input
    await prefs.setString(
      _eValueKey,
      _eValue?.toString() ?? '',
    ); // Simpan nilai BigInt
    await prefs.setString(_messageKey, _messageController.text);
    await prefs.setString(_cipherInputKey, _cipherInputController.text);
    await prefs.setInt(_currentModeKey, _currentMode.index);
    await prefs.setString(_nKey, _n?.toString() ?? '');
    await prefs.setString(_phiKey, _phi?.toString() ?? '');
    await prefs.setString(_dKey, _d?.toString() ?? '');
    await prefs.setBool(_generatedKeysVisibleKey, _generatedKeysVisible);
    await prefs.setBool(_isAutoGeneratedKey, _isAutoGenerated);
  }

  // ============================
  // 📥 Fungsi untuk memuat data dari SharedPreferences
  // ============================
  Future<void> _loadData() async {
    final prefs = await SharedPreferences.getInstance();
    setState(() {
      _pController.text = prefs.getString(_pKey) ?? '';
      _qController.text = prefs.getString(_qKey) ?? '';
      _eInputController.text =
          prefs.getString(_eInputKey) ?? ''; // Muat teks input
      _eValue = BigInt.tryParse(
        prefs.getString(_eValueKey) ?? '',
      ); // Muat nilai BigInt
      _messageController.text = prefs.getString(_messageKey) ?? '';
      _cipherInputController.text = prefs.getString(_cipherInputKey) ?? '';
      _currentMode = CipherMode.values[prefs.getInt(_currentModeKey) ?? 0];
      _n = BigInt.tryParse(prefs.getString(_nKey) ?? '');
      _phi = BigInt.tryParse(prefs.getString(_phiKey) ?? '');
      _d = BigInt.tryParse(prefs.getString(_dKey) ?? '');
      _generatedKeysVisible = prefs.getBool(_generatedKeysVisibleKey) ?? false;
      _isAutoGenerated = prefs.getBool(_isAutoGeneratedKey) ?? false;

      // Coba generate kunci jika input kunci ada
      if (_pController.text.isNotEmpty &&
          _qController.text.isNotEmpty &&
          _eInputController.text.isNotEmpty) {
        _generateKeys(
          silent: true,
          autoGenerate: _isAutoGenerated,
        ); // Generate kunci secara diam-diam, pertahankan status auto-generated
      }

      // Re-calculate result based on loaded data and mode
      if (_n != null && _d != null && _eValue != null) {
        if (_currentMode == CipherMode.encrypt &&
            _messageController.text.isNotEmpty) {
          _processCipher(silent: true);
        } else if (_currentMode == CipherMode.decrypt &&
            _cipherInputController.text.isNotEmpty) {
          _processCipher(silent: true);
        }
      }
    });
  }

  // ============================
  // 🔄 Fungsi untuk mengosongkan semua input dan hasil
  // ============================
  void _clearAll() {
    setState(() {
      _pController.clear();
      _qController.clear();
      _eInputController.clear(); // Diperbarui
      _messageController.clear();
      _cipherInputController.clear();
      _result = '';
      _n = null;
      _phi = null;
      _eValue = null; // Dikosongkan
      _d = null;
      _currentMode = CipherMode.encrypt; // Reset mode to encrypt
      _generatedKeysVisible = false;
      _errorMessage = '';
      _isAutoGenerated = false; // Reset status auto-generated
    });
    _saveData(); // Simpan state yang sudah dikosongkan
    if (mounted) {
      // Ditambahkan mounted check
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Semua input dan hasil telah dikosongkan!'),
        ),
      );
    }
  }

  // ========================================
  // 🔑 Fungsi Pembantu Matematika RSA
  // ========================================

  // Cek apakah bilangan prima (sangat dasar, tidak untuk produksi)
  bool _isPrime(BigInt n) {
    if (n <= BigInt.one) {
      return false;
    }
    if (n <= BigInt.from(3)) {
      return true;
    } // 2 and 3 are prime
    if (n % BigInt.two == BigInt.zero || n % BigInt.from(3) == BigInt.zero) {
      return false;
    } // multiples of 2 or 3

    for (BigInt i = BigInt.from(5); i * i <= n; i += BigInt.from(6)) {
      if (n % i == BigInt.zero || n % (i + BigInt.two) == BigInt.zero) {
        return false;
      }
    }
    return true;
  }

  // Greatest Common Divisor (GCD)
  BigInt _gcd(BigInt a, BigInt b) {
    while (b != BigInt.zero) {
      final t = b;
      b = a % b;
      a = t;
    }
    return a;
  }

  // Modular Multiplicative Inverse (Extended Euclidean Algorithm)
  BigInt _modInverse(BigInt a, BigInt m) {
    BigInt m0 = m;
    BigInt y = BigInt.zero, x = BigInt.one;

    if (m == BigInt.one) {
      return BigInt.zero;
    }

    while (a > BigInt.one) {
      BigInt q = a ~/ m;
      BigInt t = m;

      m = a % m;
      a = t;
      t = y;

      y = x - q * y;
      x = t;
    }

    if (x < BigInt.zero) {
      x += m0;
    }
    return x;
  }

  // Helper untuk menghasilkan BigInt acak dalam rentang
  BigInt _generateRandomBigInt(BigInt min, BigInt max) {
    final random = Random();
    // Calculate the range size
    BigInt range = max - min;
    // Generate a random number from 0 to range
    BigInt randomValue = BigInt.zero;
    int bitLength = range.bitLength;
    if (bitLength > 0) {
      // Generate a BigInt with random bits up to bitLength
      // This is a simplified approach, for truly cryptographically secure random numbers,
      // more robust methods are needed.
      for (int i = 0; i < bitLength; i++) {
        if (random.nextBool()) {
          randomValue |= (BigInt.one << i);
        }
      }
    }
    // Ensure randomValue is within the range
    if (randomValue > range) {
      randomValue %= (range + BigInt.one);
    }
    return min + randomValue;
  }

  // ========================================
  // 🔑 Key Generation (Manual & Auto)
  // ========================================
  void _generateKeys({bool silent = false, bool autoGenerate = false}) {
    setState(() {
      _errorMessage = '';
      _n = null;
      _phi = null;
      _eValue = null; // Dikosongkan
      _d = null;
      _generatedKeysVisible = false;
      _isAutoGenerated = autoGenerate; // Set status auto-generated
    });

    BigInt p, q, e;

    if (autoGenerate) {
      // Clear manual inputs when auto-generating
      _pController.clear();
      _qController.clear();
      _eInputController.clear();

      // Rentang untuk bilangan prima acak (untuk demo)
      // PENTING: Untuk keamanan nyata, ini harus ratusan digit!
      // Untuk demo, pastikan N cukup besar untuk karakter ASCII (max 127)
      // N = p * q, jadi p dan q harus cukup besar agar p*q > 127
      BigInt minPrime = BigInt.from(15); // Minimal 15 agar N > 127
      BigInt maxPrime = BigInt.from(100); // Batasi agar tidak terlalu besar

      do {
        p = _generateRandomPrime(minPrime, maxPrime);
        q = _generateRandomPrime(minPrime, maxPrime);
      } while (p == q); // Pastikan p dan q berbeda

      final n = p * q;
      final phi = (p - BigInt.one) * (q - BigInt.one);

      // Cari e yang koprima dengan phi (misal, mulai dari 3)
      e = BigInt.from(3);
      while (_gcd(e, phi) != BigInt.one) {
        e += BigInt.two; // Coba bilangan ganjil berikutnya
        if (e >= phi) {
          // Jika tidak ditemukan e yang cocok, coba lagi dengan p, q baru
          if (!silent) {
            setState(() {
              _errorMessage =
                  'Gagal menemukan E yang cocok. Coba lagi atau gunakan P, Q yang berbeda.';
            });
          }
          return;
        }
      }

      // Isi controller dengan nilai yang dihasilkan
      _pController.text = p.toString();
      _qController.text = q.toString();
      _eInputController.text = e.toString();
    } else {
      // Manual input
      final pStr = _pController.text.trim();
      final qStr = _qController.text.trim();
      final eStr = _eInputController.text.trim();

      if (pStr.isEmpty || qStr.isEmpty || eStr.isEmpty) {
        if (!silent) {
          setState(() {
            _errorMessage = 'Semua nilai kunci (p, q, e) harus diisi.';
          });
        }
        return;
      }

      final parsedP = BigInt.tryParse(pStr);
      final parsedQ = BigInt.tryParse(qStr);
      final parsedE = BigInt.tryParse(eStr);

      if (parsedP == null || parsedQ == null || parsedE == null) {
        if (!silent) {
          setState(() {
            _errorMessage = 'Nilai kunci harus berupa angka.';
          });
        }
        return;
      }
      p = parsedP;
      q = parsedQ;
      e = parsedE;
    }

    if (p < BigInt.from(10) || q < BigInt.from(10)) {
      if (!silent) {
        setState(() {
          _errorMessage =
              'P dan Q harus bilangan prima yang cukup besar (minimal 10 untuk demo).';
        });
      }
      return;
    }

    if (p == q) {
      if (!silent) {
        setState(() {
          _errorMessage = 'P dan Q tidak boleh sama.';
        });
      }
      return;
    }

    if (!_isPrime(p) || !_isPrime(q)) {
      if (!silent) {
        setState(() {
          _errorMessage = 'P dan Q harus bilangan prima.';
        });
      }
      return;
    }

    final n = p * q;
    final phi = (p - BigInt.one) * (q - BigInt.one);

    if (e < BigInt.one || e >= phi) {
      if (!silent) {
        setState(() {
          _errorMessage =
              'E harus lebih besar dari 1 dan lebih kecil dari Phi.';
        });
      }
      return;
    }

    if (_gcd(e, phi) != BigInt.one) {
      if (!silent) {
        setState(() {
          _errorMessage = 'E harus koprima dengan Phi (gcd(e, phi) harus 1).';
        });
      }
      return;
    }

    final d = _modInverse(e, phi);

    setState(() {
      _n = n;
      _phi = phi;
      _eValue = e; // Tetapkan 'e' lokal ke anggota '_eValue'
      _d = d;
      _generatedKeysVisible = true;
      _errorMessage = ''; // Hapus error sebelumnya
    });
    _saveData();
    if (!silent && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            autoGenerate
                ? 'Kunci RSA otomatis berhasil dibuat!'
                : 'Kunci RSA manual berhasil dibuat!',
          ),
        ),
      );
    }
  }

  // Helper untuk menghasilkan bilangan prima acak dalam rentang
  BigInt _generateRandomPrime(BigInt min, BigInt max) {
    BigInt candidate;
    final random = Random();
    do {
      // Generate random BigInt within the range [min, max]
      BigInt range = max - min;
      BigInt randomValue = BigInt.zero;
      int bitLength = range.bitLength;
      if (bitLength > 0) {
        for (int i = 0; i < bitLength; i++) {
          if (random.nextBool()) {
            randomValue |= (BigInt.one << i);
          }
        }
      }
      if (randomValue > range) {
        randomValue %= (range + BigInt.one);
      }
      candidate = min + randomValue;

      // Ensure it's odd (except for 2) and within bounds
      if (candidate % BigInt.two == BigInt.zero && candidate > BigInt.two) {
        candidate += BigInt.one;
      }
      if (candidate < min) candidate = min; // Ensure it's not less than min
      if (candidate > max) candidate = max; // Ensure it's not more than max
    } while (!_isPrime(candidate));
    return candidate;
  }

  // ========================================
  // 🔒 Enkripsi RSA
  // ========================================
  String _encrypt(String message) {
    if (_n == null || _eValue == null) {
      setState(() {
        _errorMessage = 'Kunci publik (n dan e) belum tersedia.';
      });
      return '';
    }

    final n = _n!;
    final e = _eValue!; // Gunakan _eValue

    // Konversi pesan ke angka (ASCII) dan enkripsi
    List<String> encryptedBlocks = [];
    for (int i = 0; i < message.length; i++) {
      BigInt charCode = BigInt.from(message.codeUnitAt(i));

      // Penting: Periksa apakah charCode < N
      if (charCode >= n) {
        setState(() {
          _errorMessage =
              'Karakter "${message[i]}" (ASCII $charCode) terlalu besar untuk N ($n). Pilih P dan Q yang lebih besar.';
        });
        return '';
      }
      BigInt encryptedChar = charCode.modPow(e, n);
      encryptedBlocks.add(encryptedChar.toString());
    }
    return encryptedBlocks.join(' ');
  }

  // ========================================
  // 🔓 Dekripsi RSA
  // ========================================
  String _decrypt(String cipherText) {
    if (_n == null || _d == null) {
      setState(() {
        _errorMessage = 'Kunci privat (n dan d) belum tersedia.';
      });
      return '';
    }

    final n = _n!;
    final d = _d!;

    // Pisahkan blok angka dan dekripsi
    List<String> cipherBlocks = cipherText.trim().split(' ');
    List<int> decryptedCharCodes = [];

    for (String block in cipherBlocks) {
      BigInt? encryptedChar = BigInt.tryParse(block);
      if (encryptedChar == null) {
        setState(() {
          _errorMessage = 'Ciphertext mengandung nilai non-angka: "$block".';
        });
        return '';
      }

      // Penting: Periksa apakah encryptedChar < N
      if (encryptedChar >= n) {
        setState(() {
          _errorMessage =
              'Ciphertext "$block" terlalu besar untuk N ($n). Kunci tidak cocok atau ciphertext rusak.';
        });
        return '';
      }
      BigInt decryptedChar = encryptedChar.modPow(d, n);
      decryptedCharCodes.add(decryptedChar.toInt());
    }
    return String.fromCharCodes(decryptedCharCodes);
  }

  // ========================================
  // ⚙️ Proses Enkripsi/Dekripsi Utama
  // ========================================
  void _processCipher({bool silent = false}) {
    setState(() {
      _errorMessage = ''; // Hapus error sebelumnya
    });

    if (_n == null || _d == null || _eValue == null) {
      if (!silent) {
        setState(() {
          _errorMessage = 'Harap buat kunci RSA terlebih dahulu.';
        });
      }
      return;
    }

    if (_currentMode == CipherMode.encrypt) {
      final message = _messageController.text.trim();
      if (message.isEmpty) {
        if (!silent) {
          setState(() {
            _errorMessage = 'Masukkan teks untuk dienkripsi!';
          });
        }
        return;
      }
      final encrypted = _encrypt(message);
      if (encrypted.isNotEmpty && _errorMessage.isEmpty) {
        // Only update if encryption was successful and no error
        setState(() {
          _result = encrypted;
          _cipherInputController.text =
              encrypted; // Perbarui kolom input cipher
        });
      }
    } else {
      // CipherMode.decrypt
      final cipherInput = _cipherInputController.text.trim();
      if (cipherInput.isEmpty) {
        if (!silent) {
          setState(() {
            _errorMessage = 'Masukkan teks terenkripsi untuk didekripsi!';
          });
        }
        return;
      }
      final decrypted = _decrypt(cipherInput);
      if (decrypted.isNotEmpty && _errorMessage.isEmpty) {
        // Only update if decryption was successful and no error
        setState(() {
          _result = decrypted;
          _messageController.text = decrypted; // Perbarui kolom pesan
        });
      }
    }
    _saveData();
    if (!silent && _errorMessage.isEmpty && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            _currentMode == CipherMode.encrypt
                ? 'Pesan berhasil dienkripsi!'
                : 'Pesan berhasil didekripsi!',
          ),
        ),
      );
    }
  }

  // ============================
  // 📝 Fungsi untuk membuat pesan yang akan dibagikan
  // ============================
  String _buildMessageForSharing() {
    String keyInfo = '';
    if (_n != null && _eValue != null && _d != null) {
      keyInfo = '''
*Kunci Publik (n, e):* (${_n!}, ${_eValue!})
*Kunci Privat (n, d):* (${_n!}, ${_d!})
''';
    }

    if (_currentMode == CipherMode.encrypt) {
      return '''
🔐 *Pesan Terenkripsi (RSA)*

━━━━━━━━━━━━━━━
$keyInfo
*Hasil Enkripsi:*
```$_result```

📜 *Petunjuk Dekripsi:*
Gunakan kunci privat (n, d) untuk mendekripsi pesan ini.
━━━━━━━━━━━━━━━

📘 _Pesan ini dibuat otomatis dari aplikasi Enkripsi by Defri_
''';
    } else {
      return '''
🔓 *Pesan Terdekripsi (RSA)*

━━━━━━━━━━━━━━━
$keyInfo
*Hasil Dekripsi:*
```$_result```

🔑 *Petunjuk:*
Ini adalah pesan asli setelah dekripsi menggunakan kunci privat.
━━━━━━━━━━━━━━━

📘 _Pesan ini dibuat otomatis dari aplikasi Enkripsi by Defri_
''';
    }
  }

  // ========================================
  // 💬 Kirim ke WhatsApp
  // ========================================
  Future<void> _sendToWhatsApp() async {
    if (_result.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Belum ada hasil yang bisa dikirim.')),
        );
      }
      return;
    }

    final message = _buildMessageForSharing();
    final String whatsappMessage = message.replaceAll(
      '```',
      '',
    ); // WhatsApp doesn't render ``` as code blocks

    await Clipboard.setData(ClipboardData(text: whatsappMessage));
    final encodedMessage = Uri.encodeComponent(whatsappMessage);
    final whatsappUri = Uri.parse("whatsapp://send?text=$encodedMessage");

    try {
      if (await canLaunchUrl(whatsappUri)) {
        await launchUrl(whatsappUri, mode: LaunchMode.externalApplication);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Pesan disalin dan WhatsApp dibuka!')),
          );
        }
      } else {
        final fallbackUrl = Uri.parse("https://wa.me/?text=$encodedMessage");
        await launchUrl(fallbackUrl, mode: LaunchMode.externalApplication);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Gagal membuka WhatsApp: $e')));
      }
    }
  }

  // ========================================
  // 📧 Kirim ke Gmail
  // ========================================
  Future<void> _sendToGmail() async {
    if (_result.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Belum ada hasil yang bisa dikirim.')),
        );
      }
      return;
    }

    final String message = _buildMessageForSharing();
    final String subject =
        _currentMode == CipherMode.encrypt
            ? '🔐 Encrypted Message (RSA)'
            : '🔓 Decrypted Message (RSA)';
    final String encodedSubject = Uri.encodeComponent(subject);
    final String encodedBody = Uri.encodeComponent(message);

    final Uri mailtoUri = Uri.parse(
      'mailto:?subject=$encodedSubject&body=$encodedBody',
    );

    try {
      await launchUrl(mailtoUri, mode: LaunchMode.externalApplication);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Membuka aplikasi email...')),
        );
      }
    } catch (e) {
      final webGmailUrl = Uri.parse(
        'https://mail.google.com/mail/?view=cm&fs=1&su=$encodedSubject&body=$encodedBody',
      );
      try {
        await launchUrl(webGmailUrl, mode: LaunchMode.platformDefault);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Membuka Gmail versi web...')),
          );
        }
      } catch (e2) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Gagal membuka Gmail: $e2')));
        }
      }
    }
  }

  // ========================================
  // 🧱 UI Helper Widgets (Konsisten dengan halaman cipher lainnya)
  // ========================================

  Widget _buildTextField(
    TextEditingController controller,
    String hintText,
    TextInputType keyboardType, {
    int? maxLines,
    bool readOnly = false,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha((255 * 0.08).round()), // Diperbarui
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: TextField(
        controller: controller,
        keyboardType: keyboardType,
        textInputAction: TextInputAction.done,
        style: const TextStyle(color: Colors.black87),
        maxLines: maxLines,
        readOnly: readOnly,
        decoration: InputDecoration(
          hintText: hintText,
          hintStyle: TextStyle(color: Colors.grey[500]),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 16,
            vertical: 14,
          ),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFF041413), width: 2),
          ),
          filled: true,
          fillColor: Colors.white,
        ),
      ),
    );
  }

  Widget _buildActionButton(String text, VoidCallback onPressed, Color color) {
    return ElevatedButton(
      // Removed Center widget as Expanded in Row will handle width
      onPressed: onPressed,
      style: ElevatedButton.styleFrom(
        backgroundColor: color,
        // Reduced padding for smaller size
        padding: const EdgeInsets.symmetric(
          horizontal: 25,
          vertical: 10,
        ), // Adjusted padding
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        shadowColor: Colors.black.withAlpha((255 * 0.3).round()),
        elevation: 8,
      ),
      child: Text(
        text,
        textAlign: TextAlign.center, // Ensure text is centered
        style: const TextStyle(
          fontSize: 15, // Slightly smaller font for smaller button
          color: Colors.white,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildResultContainer(String text) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha((255 * 0.1).round()), // Diperbarui
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: SelectableText(
        text,
        style: const TextStyle(color: Colors.black87, fontSize: 16),
      ),
    );
  }

  Widget _buildCopyButtons() {
    return Row(
      children: [
        Expanded(
          child: ElevatedButton.icon(
            onPressed: () {
              Clipboard.setData(ClipboardData(text: _result));
              if (mounted) {
                ScaffoldMessenger.of(
                  context,
                ).showSnackBar(const SnackBar(content: Text('Hasil disalin!')));
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF041413),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              shadowColor: Colors.black.withAlpha(
                (255 * 0.2).round(),
              ), // Diperbarui
              elevation: 4,
            ),
            icon: const Icon(Icons.copy, size: 18),
            label: const Text(
              'Salin Hasil',
              style: TextStyle(fontWeight: FontWeight.w500),
            ),
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: ElevatedButton.icon(
            onPressed: () {
              final info =
                  _currentMode == CipherMode.encrypt
                      ? 'Gunakan kunci privat (n, d) untuk mendekripsi pesan ini.'
                      : 'Ini adalah pesan asli setelah dekripsi menggunakan kunci privat.';
              Clipboard.setData(ClipboardData(text: info));
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Petunjuk disalin!')),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF041413),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              shadowColor: Colors.black.withAlpha(
                (255 * 0.2).round(),
              ), // Diperbarui
              elevation: 4,
            ),
            icon: const Icon(Icons.info_outline, size: 18),
            label: const Text(
              'Salin Petunjuk',
              style: TextStyle(fontWeight: FontWeight.w500),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSocialButton(String assetPath, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: 65,
        height: 65,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withAlpha((255 * 0.15).round()), // Diperbarui
              blurRadius: 8,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Center(
          child: SvgPicture.asset(assetPath, width: 32, height: 32),
        ),
      ),
    );
  }

  // ========================================
  // 🧱 UI Utama
  // ========================================
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      backgroundColor: const Color(0xFFE6E6E6),
      body: SafeArea(
        child: Column(
          children: [
            // HEADER
            Container(
              height: 70,
              width: double.infinity,
              color: const Color(0xFF041413),
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Positioned(
                    left: 12,
                    child: IconButton(
                      icon: const Icon(
                        Icons.arrow_back_ios_new_rounded,
                        color: Colors.white,
                      ),
                      iconSize: 24,
                      onPressed: () => Navigator.pop(context),
                    ),
                  ),
                  SvgPicture.asset(
                    'assets/images/logoenkripsiapps.svg',
                    width: 50,
                    height: 50,
                  ),
                  Positioned(
                    right: 12,
                    child: IconButton(
                      icon: const Icon(Icons.refresh, color: Colors.white),
                      iconSize: 24,
                      onPressed: _clearAll,
                    ),
                  ),
                ],
              ),
            ),

            // Mode Toggle
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 20.0,
                vertical: 15.0,
              ),
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.all(4),
                decoration: BoxDecoration(
                  color: Colors.grey[200],
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withAlpha(
                        (255 * 0.08).round(),
                      ), // Diperbarui
                      blurRadius: 6,
                      offset: const Offset(0, 3),
                    ),
                  ],
                ),
                child: LayoutBuilder(
                  builder: (context, constraints) {
                    final buttonWidth = (constraints.maxWidth - 8) / 2;

                    return ToggleButtons(
                      isSelected: [
                        _currentMode == CipherMode.encrypt,
                        _currentMode == CipherMode.decrypt,
                      ],
                      onPressed: (index) {
                        setState(() {
                          _currentMode =
                              index == 0
                                  ? CipherMode.encrypt
                                  : CipherMode.decrypt;
                          _errorMessage = ''; // Hapus error saat mengganti mode
                          // Clear relevant input fields when switching mode
                          if (_currentMode == CipherMode.encrypt) {
                            _cipherInputController.clear();
                          } else {
                            _messageController.clear();
                          }
                          _result = ''; // Clear result
                        });
                        _saveData();
                      },
                      borderRadius: BorderRadius.circular(10),
                      selectedColor: Colors.white,
                      color: Colors.black87,
                      fillColor: const Color(0xFF041413),
                      borderColor: Colors.transparent,
                      selectedBorderColor: Colors.transparent,
                      splashColor: const Color(
                        0xFF041413,
                      ).withAlpha((255 * 0.2).round()), // Diperbarui
                      highlightColor: const Color(
                        0xFF041413,
                      ).withAlpha((255 * 0.1).round()), // Diperbarui
                      children: [
                        SizedBox(
                          width: buttonWidth,
                          child: const Center(
                            child: Padding(
                              padding: EdgeInsets.symmetric(
                                horizontal: 10,
                                vertical: 10,
                              ),
                              child: Text(
                                'Enkripsi',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: buttonWidth,
                          child: const Center(
                            child: Padding(
                              padding: EdgeInsets.symmetric(
                                horizontal: 10,
                                vertical: 10,
                              ),
                              child: Text(
                                'Dekripsi',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
            ),

            // BODY
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (_errorMessage.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 15.0),
                        child: Text(
                          _errorMessage,
                          style: const TextStyle(
                            color: Colors.red,
                            fontSize: 14,
                          ),
                        ),
                      ),
                    const Text(
                      'Input Kunci RSA (P, Q, E):',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: Colors.black87,
                      ),
                    ),
                    const SizedBox(height: 10),
                    _buildTextField(
                      _pController,
                      'Bilangan prima P (misal: 61)',
                      TextInputType.number,
                      readOnly: _isAutoGenerated, // Read-only jika otomatis
                    ),
                    const SizedBox(height: 10),
                    _buildTextField(
                      _qController,
                      'Bilangan prima Q (misal: 53)',
                      TextInputType.number,
                      readOnly: _isAutoGenerated, // Read-only jika otomatis
                    ),
                    const SizedBox(height: 10),
                    _buildTextField(
                      _eInputController, // Diperbarui
                      'E (public exponent, misal: 17)',
                      TextInputType.number,
                      readOnly: _isAutoGenerated, // Read-only jika otomatis
                    ),
                    const SizedBox(height: 20),

                    // Tombol Buat Kunci hanya muncul di mode Enkripsi
                    if (_currentMode == CipherMode.encrypt)
                      Row(
                        children: [
                          Expanded(
                            child: _buildActionButton(
                              'Buat Kunci Manual',
                              () => _generateKeys(autoGenerate: false),
                              const Color(0xFF041413),
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: _buildActionButton(
                              'Buat Kunci Otomatis',
                              () => _generateKeys(autoGenerate: true),
                              const Color(
                                0xFF455A64,
                              ), // Warna baru (Colors.blueGrey.shade700)
                            ),
                          ),
                        ],
                      ),
                    const SizedBox(height: 24),

                    if (_generatedKeysVisible) ...[
                      const Text(
                        'Kunci RSA yang Dihasilkan:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildResultContainer(
                        'n (modulus): ${_n ?? 'N/A'}\n'
                        'phi (totient): ${_phi ?? 'N/A'}\n'
                        'e (public exponent): ${_eValue ?? 'N/A'}\n' // Diperbarui
                        'd (private exponent): ${_d ?? 'N/A'}',
                      ),
                      const SizedBox(height: 24),
                    ],

                    if (_currentMode == CipherMode.encrypt) ...[
                      const Text(
                        'Masukkan teks untuk dienkripsi:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildTextField(
                        _messageController,
                        'Tulis teks...',
                        TextInputType.text,
                        maxLines: 3,
                      ),
                      const SizedBox(height: 20),
                      Center(
                        child: _buildActionButton(
                          'Enkripsi Sekarang',
                          _processCipher,
                          const Color(0xFF041413),
                        ),
                      ),
                      const SizedBox(height: 24),
                      const Text(
                        'Hasil Enkripsi:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildResultContainer(
                        _result.isEmpty
                            ? 'Hasil akan muncul di sini...'
                            : _result,
                      ),
                    ] else ...[
                      // UI untuk Dekripsi
                      const Text(
                        'Masukkan teks terenkripsi (angka dipisah spasi):',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildTextField(
                        _cipherInputController,
                        'Tulis teks terenkripsi (misal: 123 456 789)',
                        TextInputType.text,
                        maxLines: 3,
                      ),
                      const SizedBox(height: 20),
                      Center(
                        child: _buildActionButton(
                          'Dekripsi Sekarang',
                          _processCipher,
                          const Color(0xFF041413),
                        ),
                      ),
                      const SizedBox(height: 24),
                      const Text(
                        'Hasil Dekripsi:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 10),
                      _buildResultContainer(
                        _result.isEmpty
                            ? 'Hasil akan muncul di sini...'
                            : _result,
                      ),
                    ],
                    const SizedBox(height: 10),
                    if (_result.isNotEmpty) _buildCopyButtons(),

                    const SizedBox(height: 30),
                    const Divider(color: Colors.black12, thickness: 1.5),
                    const SizedBox(height: 8),
                    const Text(
                      '📘 Penjelasan Kriptografi:',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                        color: Colors.black87,
                      ),
                    ),
                    const SizedBox(height: 6),
                    const SelectableText(
                      'RSA (Rivest–Shamir–Adleman) adalah algoritma kriptografi kunci publik. '
                      'Ini berarti ada dua kunci: kunci publik untuk enkripsi (bisa dibagikan) dan kunci privat untuk dekripsi (harus dirahasiakan). '
                      'RSA bekerja berdasarkan kesulitan memfaktorkan hasil kali dua bilangan prima besar. '
                      'Prosesnya melibatkan pemilihan dua bilangan prima (p dan q), menghitung modulus (n = p * q) dan totient (phi = (p-1)*(q-1)), '
                      'lalu memilih public exponent (e) dan menghitung private exponent (d) sebagai invers modular dari e terhadap phi. '
                      'Enkripsi: C = M^e mod n. Dekripsi: M = C^d mod n. '
                      'Untuk tujuan demo ini, kami menggunakan bilangan prima kecil yang tidak aman untuk penggunaan nyata. '
                      'Penting: Setiap karakter yang dienkripsi harus memiliki nilai ASCII/Unicode yang lebih kecil dari modulus N (p*q).',
                      style: TextStyle(color: Colors.black87, height: 1.4),
                    ),
                    const SizedBox(height: 32),
                    Center(
                      child: Column(
                        children: [
                          const Text(
                            'Kirim hasil ke',
                            style: TextStyle(
                              fontSize: 17,
                              fontWeight: FontWeight.w700,
                              color: Colors.black87,
                            ),
                          ),
                          const SizedBox(height: 10),
                          Container(
                            width: 180,
                            height: 1.5,
                            color: Colors.black26,
                          ),
                          const SizedBox(height: 20),
                          // 🔗 Sosial
                          Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              _buildSocialButton(
                                'assets/images/wa.svg',
                                _sendToWhatsApp,
                              ),
                              const SizedBox(width: 40),
                              _buildSocialButton(
                                'assets/images/gmail.svg',
                                _sendToGmail,
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
